# Generated by Claude Sonnet 4.6 (claude-sonnet-4-6) via claude.ai
#
# Prompts used (in order):
# 1. "Code a godot tool script which generates a staircase from csg. The staircase
#     shouldn't be a ramp, but a real staircase with steps. The height, width and
#     length and number of steps is configurable"
# 2. "Is there a way to make it also visible in the editor and actually a custom class?"
# 3. "Can you hide the step nodes in the editor?"

@tool
extends CSGCombiner3D
class_name CSGStairCase

## Staircase Generator
## Add directly from the "Add Node" dialog — search for "StaircaseGenerator".
## Staircase rises along +Y and extends along +Z, centred on X.

@export_group("Staircase Dimensions")

## Total height of the staircase
@export var total_height: float = 3.0:
	set(v):
		total_height = max(v, 0.1)
		_rebuild()

## Total length (depth) along the Z axis
@export var total_length: float = 4.0:
	set(v):
		total_length = max(v, 0.1)
		_rebuild()

## Width along the X axis
@export var total_width: float = 2.0:
	set(v):
		total_width = max(v, 0.1)
		_rebuild()

## Number of steps
@export var num_steps: int = 8:
	set(v):
		num_steps = max(v, 1)
		_rebuild()

@export_group("Options")

## true  → solid stacked blocks (looks solid from the side)
## false → thin individual treads only
@export var solid_blocks: bool = true:
	set(v):
		solid_blocks = v
		_rebuild()

## Optional material applied to every step
@export var step_material: Material = null:
	set(v):
		step_material = v
		_rebuild()

# ------------------------------------------------------------------

func _ready() -> void:
	_rebuild()


func _rebuild() -> void:
	# Property setters fire before the node enters the scene tree,
	# so guard here to avoid errors on initial load.
	if not is_inside_tree():
		return

	# Use free() instead of queue_free() — the deferred version leaves
	# ghost nodes alive for one frame, which breaks in-editor rebuilds.
	# get_children(true) includes internal nodes, which is what we need here.
	for child in get_children(true):
		child.free()

	if num_steps <= 0:
		return

	var step_height: float = total_height / num_steps
	var step_depth:  float = total_length / num_steps

	for i in range(num_steps):
		var box := CSGBox3D.new()
		# INTERNAL_MODE_BACK hides the node from the Scene panel and
		# excludes it from the .tscn file — the script recreates it on load.
		add_child(box, false, INTERNAL_MODE_BACK)

		if solid_blocks:
			# Stacked solid block from the floor up to tread level.
			var block_height: float = step_height * (i + 1)
			box.size     = Vector3(total_width, block_height, step_depth)
			box.position = Vector3(
				0.0,
				block_height * 0.5,
				step_depth * i + step_depth * 0.5
			)
		else:
			# Thin tread only.
			var tread_thickness: float = clamp(step_height * 0.15, 0.02, 0.1)
			box.size     = Vector3(total_width, tread_thickness, step_depth)
			box.position = Vector3(
				0.0,
				step_height * (i + 1) - tread_thickness * 0.5,
				step_depth * i + step_depth * 0.5
			)

		if step_material:
			box.material = step_material
